# DialogPlugin - 对话框菜单插件配置文件
# 作者: cxkcxkckx
# 注意: 默认菜单名称为 "default"，使用 /ui 命令可直接打开 default.json 菜单

# 日志设置
logging:
  # 是否在控制台输出详细日志
  console: false
  # 是否记录动作执行日志
  actions: false
  # 是否记录菜单操作日志
  menu: false
  # 是否记录错误日志
  errors: false

# 消息设置
messages:
  # 是否向玩家发送动作执行成功消息
  success: false
  # 是否向玩家发送动作执行失败消息
  failure: false
  # 是否向玩家发送命令执行成功消息
  command_success: false
  # 是否向玩家发送传送成功消息
  teleport_success: false
  # 是否向玩家发送物品获得消息
  item_success: false 