name: DialogPlugin
version: '1.0.0-SNAPSHOT'
main: alepando.dev.dialogPlugin.DialogPlugin
api-version: '1.21'
authors:
  - cxkcxkckx

commands:
  test:
    description: test command
    usage: /<command>
  ui:
    description: 打开自定义菜单
    usage: /<command> <菜单名>
  uireload:
    description: 重载菜单配置
    usage: /<command>
    permission: dialogplugin.reload
  uihelp:
    description: 显示帮助信息
    usage: /<command>

permissions:
  dialogplugin.reload:
    description: 允许重载菜单配置
    default: op
